### ISSUE TITLE
how about update to 0.9.2

### ISSUE THREAD

**Issue by xiejinglan** [libretro/melonDS#109]

**Comment by ToniBC** [comment]
We are already in 0.9.3 and nothing, we keep waiting. Something is happening with many cores that are not updated and lag behind a lot. In particular, this one does not have much movement, but the improvements are usually interesting.

They are surely focused on the PS2 core and have the rest a bit neglected.

Hopefully it will be updated soon.

**Comment by m4tsa** [comment]
The core has been rebased on 0.9.3 and the next build should reflect that.
