### ISSUE TITLE
Sound Pops on Content Launch [Regression]

### ISSUE THREAD

**Issue by Awakened0** [libretro/melonDS#127]
After the latest rebase, there are some loud sound pops on launching content. I'm using real DS BIOS/Firmware, software rendering and RetroArch's vulkan driver. I've found the pops are louder when using the vulkan driver compared to d3d11. Audio bitrate and Interpolation are left at their defaults (Automatic, None).

Comparison of 0.9.1 657c729 to 0.9.3 27ee883:

https://user-images.githubusercontent.com/4565863/135181247-7076c6f0-1d5c-40b3-b91b-68a14c2f898a.mp4

https://user-images.githubusercontent.com/4565863/135181254-f252d199-cc55-4659-bd22-1cc9e02b8e26.mp4

**Comment by stuken** [comment]
This also happens on the upstream 0.9.3 version. Boot the firmware directly and you will hear the same pops.

**Comment by Awakened0** [comment]
> 
> 
> This also happens on the upstream 0.9.3 version. Boot the firmware directly and you will hear the same pops.

Confirmed. Closing this since it's an upstream issue.
