### ISSUE TITLE
RetroAchievements support is broken

### ISSUE THREAD

**Issue by GenericMadScientist** [libretro/melonDS#140]
A recent update to this core broke RetroAchievements support. As of writing the latest version is broken, while it works fine in 0.9.3 1ad6572. When I brought this up in the libretro server I was informed that the commit that broke achievement support is 02f0f0d, hopefully this is helpful.

**Comment by m4tsa** [comment]
@stuken, could you take a look at this?

**Comment by stuken** [comment]
In the meantime the stable core package for [1.9.14](https://buildbot.libretro.com/stable/1.9.14/windows/x86_64/) has a compatible build, minus the slot 1/2 booting and softpatching support that can be used until the changes reach retroarch.

**Comment by Jamiras** [comment]
You might want to consider implementing [`RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE`](https://github.com/libretro/RetroArch/pull/12473) and setting the `persistent_data` flag to true to avoid duplicating the already-loaded-in-memory ROM data. Cloning 256MB may be taxing on some systems.
