### ISSUE TITLE
Update the core upsatream

### ISSUE THREAD

**Issue by Eduxki** [libretro/melonDS#162]
The core is not updated, save states using dsi mode don't work but that's been fixed on standalone.

You just have to upstream some commits, read about it in retroarch discord. I've talked to the devs, you just have to revert the free bios and upstream with the main fork.

**Comment by ToniBC** [comment]
Hopefully the maintainers of the cores will update it to 0.9.4. The core does not load the dsiware either, among other bugs that have already been repaired as you mentioned in the latest version.

**Comment by QcSamuel** [comment]
Welcome to Retroarch drama and outdated cores

**Comment by ez-me** [comment]
Upstream is now on 0.9.5, which fixes some more performance, compatibility, and better DSi support.

It'd be great if the core got updated, as it would help people who don't use the Desktop version (namely mobile devices and other consoles)

**Comment by Eduxki** [comment]
well it  is obvious it not gonna happen, lets hope standalone adds retroachievements and that unofficial Android port keep improving .
