### ISSUE TITLE
Update MelonDS

### ISSUE THREAD

**Issue by RobLoach** [libretro/melonDS#32]
There's been a few changes since the last update.

**Comment by RobLoach** [comment]
https://www.reddit.com/r/emulation/comments/b5kodh

**Comment by fr500** [comment]
pcap dependency is a problem

**Comment by Papermanzero** [comment]
Is it possible to update to the latest release? Melonds has great performance compared to desmume.

**Comment by Mr-Jake** [comment]
If pcap dependency is a problem, could the code be stripped out. Wifi and network features would be disabled, but version 0.8.1 has quite a few fixes and graphic enhancements.

**Comment by Papermanzero** [comment]
Why not delete the pcap dependencies? It is only for network traffic and management. For the remaining features it is not relevant.

**Comment by Datamats** [comment]
The core has been rebased and is now up to date with the current upstream
