### ISSUE TITLE
There's no stylus or cursor. No way to play games needing a touchscreen.

### ISSUE THREAD

**Issue by Cee123** [libretro/melonDS#36]
How are you supposed to play games that need a touchscreen or use of the stylus? With Desmume, you can use the mouse cursor/click to emulate the touchscreen. I cannot find an option with this emulator.

**Comment by Datamats** [comment]
there is a variable for it now, if you wait for the next nightly release

**Comment by Cee123** [comment]
@Datamats Awesome! Thank you you're a legend. I'll try the next release. Thanks so much.

**Comment by Cee123** [comment]
@Datamats I just came back to say thank you. It works very well!
