### ISSUE TITLE
MelonDS quits retroarch

### ISSUE THREAD

**Issue by Papermanzero** [libretro/melonDS#39]
If I try to run a game with melonds (release from today) than retroarch is going to close.
Means I cannot run any game with melonds. Tested with windows 10 build

**Comment by Datamats** [comment]
ensure you have bios7.bin, bios9.bin and firmware.bin in the retroarch system directory. A more descriptive error should probably be implemented and I'll look into it rn

**Comment by Papermanzero** [comment]
I have now the bios/firmware files in place. However i cannot start the game. At least retroarch does not quit. But it seems melonds does not load the game.
Meanwhile i can see the build version which is: 46d1d88

**Comment by Datamats** [comment]
I just tried a fresh RetroArch install on Windows 10, after updating via the core updater I got 6e27160 and it worked fine for me, sure you have a valid bios/firmware and rom?

**Comment by Papermanzero** [comment]
You are right. It was a naming issue. 
I named the bios in a wrong manner.
Sorry, my fault. Now it is working
