### ISSUE TITLE
High Resolution Setting for Windows

### ISSUE THREAD

**Issue by Papermanzero** [libretro/melonDS#43]
Adding a core options to adjust the internal resolution.

**Comment by Datamats** [comment]
You can change the resolution with the opengl renderer, but currently it is only compiled for unix systems since I have no experience in getting OpenGL to work on Windows.

**Comment by Papermanzero** [comment]
But the core setting is missing. Am i right?

**Comment by Datamats** [comment]
It's not missing from the core itself. But it is conditionally compiled and not enabled for the Windows platform.

**Comment by Papermanzero** [comment]
Ah. I see. Thanks for clarification 😊

**Comment by Immersion95** [comment]
This issue should be closed.
