### ISSUE TITLE
Content failing to continue because of save-related issue ("could not erase data")

### ISSUE THREAD

**Issue by Ryunam** [libretro/melonDS#44]
I am experiencing an issue affecting the entirety of the content I have tried so far with this core. Here's what happens:

- content is loaded at first and video shows correctly;
- after the initial title screen / splash screen (depending on each content) a save-related error comes up, indicating that the system could not "erase data" and suggesting to reinsert the Game Card;
- there's no way to make the content actually continue running after this error is shown.

Here's an example of what I am seeing with the European version of New Super Mario Bros.: https://i.imgur.com/acOSZ9M.png

This is happening with all core-options set to their default values and with runahead disabled. I have also tried changing the savefile directory to other paths, but to no avail.

**Comment by Ryunam** [comment]
I managed to make it work by generating .sav files through standalone melonds 0.8.2 and then placing those .sav files in the libretro core saves directory. Only when doing that, everything works.
For some reason the core is not creating these .sav files from scratch when starting content for the first time.

**Comment by Datamats** [comment]
Should be fixed when #46 gets merged and the next nightly comes out. Feel free to reopen if the issue persists
