### ISSUE TITLE
System/BIOS Settings Aren't Saved

### ISSUE THREAD

**Issue by Awakened0** [libretro/melonDS#51]
Changes to things in the system menu like Language or User Name aren't being saved/loaded. I see a firmware.bin.bak file is being created in the system folder. Not sure if that's where it's supposed to store them or not.

**Comment by Awakened0** [comment]
I see there is a firmware.bin put in the RetroArch root folder as well. Maybe that's the one that is supposed to be used? It should be put in system or save. Desmume puts a firmware.dfc file in the save directory that stores firmware settings.

**Comment by Datamats** [comment]
Fixed by #53 and should be working in the next batch of nightlies

**Comment by Awakened0** [comment]
On windows it's crashing to desktop now. The log stops after the ARM 9 and 7 BIOS are loaded, so maybe it's having trouble loading the firmware?

**Comment by Datamats** [comment]
I just tried it on my Windows laptop and after using the core updater and verifying it's on the latest commit. I messed with the settings and everything seems to work including savegames on Windows 10.

**Comment by Awakened0** [comment]
Anything that looks weird in my verbose log?

https://pastebin.com/NQEmR1nP

**Comment by Awakened0** [comment]
Tried with a fresh extracted win64 1.7.7 stable and get a crash there too.

Log: https://pastebin.com/9cYb5W3y
Crash Log: https://pastebin.com/p9L5Xtqc
