### ISSUE TITLE
Saving Changes in Firmware Causes White Screen Freeze

### ISSUE THREAD

**Issue by Awakened0** [libretro/melonDS#58]
Steps to reproduce:

1. Go into the firmware settings (DS icon at the bottom of the screen).
2. Change the language setting to something different.
3. Let the emulated DS reboot (will get stuck on a black screen).
4. Close and reopen RetroArch.
5. When loading content again, melonDS will get stuck on a white screen.
6. Restoring the firmware.bin file from backup fixes it.

The fix for the .bak file not being present didn't fix this.

**Comment by Datamats** [comment]
I'll look at it when I arrive home, I think I see the issue and how to fix it properly this time.

**Comment by Datamats** [comment]
should be fixed in the next nightly
