### ISSUE TITLE
[Request][Windows] Add views options from standalone to the MelonDS core

### ISSUE THREAD

**Issue by Immersion95** [libretro/melonDS#61]
Hi, a lot of options regarding the views are present on standalone and missing on the core.

It would be great to add it !

MelonDS is fantastic but there is no fullscreen option on the standalone, adding all of its options on the liberetro core would provide the best experience !

**Comment by Ryunam** [comment]
It would be great to have the same Hybrid views featured in the Desmume cores. As far as I'm concerned, the Hybrid options provide the best convenience in terms of using a widescreen monitor and being able to view as much information as possible at a glance.

**Comment by Immersion95** [comment]
Solved
