### ISSUE TITLE
Savestates not working on the core.

### ISSUE THREAD

**Issue by i30817** [libretro/melonDS#66]
Just as mentioned (for Theresia, didn't check other games).
The files get created, but when trying to load them

```
savestate: bad length 6525900
savestate: VERY BAD!!!!!! EVENT FUNCTION POINTER ID 12 IS OUT OF RANGE. HAX?????
```

**Comment by Ryunam** [comment]
I believe this can be closed as a result of the newly rebased core. @i30817, can you test it with the game that gave you those errors (Theresia) and see if everything works alright now?

**Comment by i30817** [comment]
Only when the buildbot updates it, it's saying i already have the latest version.

**Comment by i30817** [comment]
Ok i got tired of waiting and got a libretro dev self build, it works.
