### ISSUE TITLE
[Feature Request] Autohide Touchscreen Cursor

### ISSUE THREAD

**Issue by Awakened0** [libretro/melonDS#69]
The touchscreen cursor in Joystick and Mouse touch modes should hide after a few seconds of not moving. This should make the Off touch mode obsolete too, since I think it's only there to hide the cursor.

**Comment by reyaz006** [comment]
It appears the feature was implemented in melonDS long ago, see https://github.com/Arisotura/melonDS/issues/935

I'm not sure why it's not available in libretro core.

**Comment by Awakened0** [comment]
I don't think it's something you can just pull from upstream. The cursor in the Libretro core was probably coded from scratch specifically for it.

**Comment by reyaz006** [comment]
Thanks for clarification. Well, if it's not easy to do, I think a viable alternative that is easier to implement would be to modify the rectangle inside of which the cursor is locked, so user might be able to move it aside from the screen when not needed.

**Comment by Awakened0** [comment]
Closing this as it's implemented in new MelonDS DS core.
