### ISSUE TITLE
Chrono Trigger DS - Crash right after introduction movie

### ISSUE THREAD

**Issue by Ryunam** [libretro/melonDS#88]
As reported in the issue title, with the latest version of this core Chrono Trigger DS will lead to a sudden segfault / crash right after the introduction movie plays out, as well as if you skip the intro movie by pressing a button or clicking on the emulated touchscreen. RetroArch will close itself suddenly. This happens regardless of the core options used.

I have yet to perform a bisect, but I am fairly certain that it used to work well not too long ago. I had tested this specific game quite a few times after the core rebase.

**Comment by Ryunam** [comment]
On second look, it seems to be related to this issue on the original repo: https://github.com/Arisotura/melonDS/issues/838.

The problem appears to have been addressed upstream by reverting commit https://github.com/Arisotura/melonDS/commit/6e8bac39091d0321f43a3e7574d3359255996e9f. When the libretro core is synchronized again with upstream, this should also be solved.

**Comment by m4tsa** [comment]
Should be fixed after the next build.
