### ISSUE TITLE
Request for libretro core build instructions

### ISSUE THREAD

**Issue by lucasmr** [libretro/melonDS#89]
I tried the following:

```
$ mkdir build
$ cd build
$ cmake ..
$ make
```

It compiles `melonDS` executable just fine, but the generated `src/libcore.a` fails to load under `Load Core` in RetroArch. What am I missing? Thanks.

**Comment by m4tsa** [comment]
the build instructions are for the upstream emulation, do not use cmake and just do `make` in the main project directory.

**Comment by lucasmr** [comment]
Alright, thanks.
